# Generated by Django 2.1.1 on 2018-09-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wips_black', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='blackList',
        ),
    ]
