# Generated by Django 2.1.1 on 2018-09-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wips_black', '0002_auto_20180914_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='mac',
            new_name='ap_mac',
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='mac_type',
            new_name='channel',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='block_stat',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='st_mac',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
