# Generated by Django 2.1.1 on 2018-10-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wips_black', '0004_auto_20180921_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='ap_auth',
            field=models.IntegerField(choices=[(-10, 'NONE'), (17, 'A_RESERVATION'), (18, 'A_8021X'), (19, 'PSK')]),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='ap_cipher',
            field=models.IntegerField(choices=[(-10, 'NONE'), (0, 'OPEN'), (11, 'GROUP_CIPHER_SUITE'), (12, 'WEP40'), (13, 'TKIP'), (14, 'C_RESERVATON'), (15, 'CCMP'), (16, 'WEP104')]),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='ap_enc',
            field=models.IntegerField(choices=[(-10, 'NONE'), (1, 'WEP'), (10, 'WPA1'), (20, 'WPA2')]),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='st_mac',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
