# Generated by Django 2.1.1 on 2018-09-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=12)),
                ('mac_type', models.IntegerField()),
            ],
        ),
    ]
