# Generated by Django 2.1.1 on 2018-10-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wips_white', '0005_auto_20181011_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='ad_hoc_stat',
            field=models.IntegerField(default=0, verbose_name=((0, 'AD_HOC OFF'), (1, 'AD_HOC ON'))),
        ),
    ]
