# Generated by Django 2.1.1 on 2018-10-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wips_white', '0006_whitelist_ad_hoc_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='ad_hoc_stat',
            field=models.IntegerField(choices=[(0, 'AD_HOC OFF'), (1, 'AD_HOC ON')], default=0),
        ),
    ]
