# Generated by Django 2.0.5 on 2018-05-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wips_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklog',
            name='mac',
            field=models.BigIntegerField(),
        ),
    ]
