# Generated by Django 2.0.5 on 2018-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wips_home', '0002_auto_20180513_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklog',
            name='mac',
            field=models.CharField(max_length=12),
        ),
    ]
