# Generated by Django 2.0.5 on 2018-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wips_home', '0003_auto_20180513_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklog',
            name='block_stat',
            field=models.BooleanField(default='False'),
        ),
    ]
